import { useState, useEffect } from 'react'
import { supabase } from '../../lib/supabase'
import Card from '../../components/ui/Card'
import { Loader2, BookOpen, Trash2, Eye } from 'lucide-react'

const LANGS = ['en', 'fr', 'it', 'es']

export default function AdminLessonsPage() {
  const [lessons, setLessons] = useState([])
  const [loading, setLoading] = useState(true)
  const [preview, setPreview] = useState(null)
  const [previewLang, setPreviewLang] = useState('en')

  useEffect(() => {
    fetchLessons()
  }, [])

  async function fetchLessons() {
    setLoading(true)
    const { data } = await supabase
      .from('daily_lessons')
      .select('*')
      .order('created_at', { ascending: false })
      .limit(100)
    setLessons(data || [])
    setLoading(false)
  }

  async function handleDelete(id) {
    if (!confirm('Delete this lesson?')) return
    await supabase.from('daily_lessons').delete().eq('id', id)
    setLessons((prev) => prev.filter((l) => l.id !== id))
  }

  return (
    <div>
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-[#1A1A1A]">Lessons</h1>
        <p className="text-sm text-[#6B7280] mt-1">
          Manage "Lesson of the Day" content generated by AI
        </p>
      </div>

      <Card>
        {loading ? (
          <div className="flex items-center justify-center py-12">
            <Loader2 size={20} className="text-[#6B7280] animate-spin" />
          </div>
        ) : lessons.length === 0 ? (
          <div className="py-12 text-center">
            <BookOpen size={32} className="mx-auto text-gray-300 mb-2" />
            <p className="text-sm text-[#6B7280]">
              No lessons yet. Generate a Daily Pack to create lessons.
            </p>
          </div>
        ) : (
          <div className="divide-y divide-gray-100">
            {lessons.map((lesson) => (
              <div
                key={lesson.id}
                className="flex items-center gap-3 py-3 px-1"
              >
                <div className="w-10 h-10 rounded-lg bg-amber-100 flex items-center justify-center shrink-0">
                  <BookOpen size={16} className="text-amber-600" />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-semibold text-gray-900 truncate">
                    {lesson.title_en || 'Untitled Lesson'}
                  </p>
                  <p className="text-xs text-gray-500">
                    {lesson.theme} ·{' '}
                    {new Date(lesson.created_at).toLocaleDateString()}
                  </p>
                </div>
                <button
                  onClick={() => {
                    setPreview(lesson)
                    setPreviewLang('en')
                  }}
                  className="p-1.5 rounded-lg text-[#6B7280] hover:bg-gray-100"
                  title="Preview"
                >
                  <Eye size={16} />
                </button>
                <button
                  onClick={() => handleDelete(lesson.id)}
                  className="p-1.5 rounded-lg text-red-400 hover:bg-red-50 hover:text-red-600"
                  title="Delete"
                >
                  <Trash2 size={16} />
                </button>
              </div>
            ))}
          </div>
        )}
      </Card>

      {/* Preview modal */}
      {preview && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4">
          <div className="bg-white rounded-2xl shadow-xl w-full max-w-lg max-h-[80vh] overflow-y-auto p-6">
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-bold">
                {preview[`title_${previewLang}`] || preview.title_en}
              </h3>
              <button
                onClick={() => setPreview(null)}
                className="text-gray-400 hover:text-gray-700 text-xl"
              >
                ×
              </button>
            </div>

            {/* Language tabs */}
            <div className="flex gap-1 mb-4">
              {LANGS.map((lng) => (
                <button
                  key={lng}
                  onClick={() => setPreviewLang(lng)}
                  className={`px-3 py-1.5 rounded-lg text-xs font-semibold uppercase transition-colors ${
                    previewLang === lng
                      ? 'bg-[#1B3D2F] text-white'
                      : 'bg-gray-100 text-[#6B7280] hover:bg-gray-200'
                  }`}
                >
                  {lng}
                </button>
              ))}
            </div>

            <div className="space-y-3">
              <p className="text-sm text-gray-700 leading-relaxed whitespace-pre-wrap">
                {preview[`content_${previewLang}`] || preview.content_en || 'No content'}
              </p>
              {(preview[`key_takeaway_${previewLang}`] || preview.key_takeaway_en) && (
                <div className="p-3 bg-amber-50 border border-amber-200 rounded-xl">
                  <p className="text-xs font-semibold text-amber-700 uppercase mb-1">Key Takeaway</p>
                  <p className="text-sm text-amber-900">
                    {preview[`key_takeaway_${previewLang}`] || preview.key_takeaway_en}
                  </p>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
