import { useState, useEffect } from 'react'
import { supabase } from '../../lib/supabase'
import Card from '../../components/ui/Card'
import { Loader2, Puzzle, Trash2, Eye } from 'lucide-react'

const PUZZLE_TYPE_LABELS = {
  tap_to_spot: 'Spot the Error',
  ab_choice: 'A/B Choice',
  fill_gap: 'Fill the Gap',
  match_chart: 'Match Chart',
  before_after: 'Before & After',
  crash_point: 'Crash Point',
}

export default function AdminPuzzlesPage() {
  const [puzzles, setPuzzles] = useState([])
  const [loading, setLoading] = useState(true)
  const [preview, setPreview] = useState(null)

  useEffect(() => {
    fetchPuzzles()
  }, [])

  async function fetchPuzzles() {
    setLoading(true)
    const { data } = await supabase
      .from('puzzles')
      .select('*')
      .order('created_at', { ascending: false })
      .limit(100)
    setPuzzles(data || [])
    setLoading(false)
  }

  async function handleDelete(id) {
    if (!confirm('Delete this puzzle?')) return
    await supabase.from('puzzles').delete().eq('id', id)
    setPuzzles((prev) => prev.filter((p) => p.id !== id))
  }

  return (
    <div>
      <div className="mb-6">
        <h1 className="text-2xl font-bold text-[#1A1A1A]">Puzzles</h1>
        <p className="text-sm text-[#6B7280] mt-1">
          Manage "The Catch" puzzles generated by AI
        </p>
      </div>

      <Card>
        {loading ? (
          <div className="flex items-center justify-center py-12">
            <Loader2 size={20} className="text-[#6B7280] animate-spin" />
          </div>
        ) : puzzles.length === 0 ? (
          <div className="py-12 text-center">
            <Puzzle size={32} className="mx-auto text-gray-300 mb-2" />
            <p className="text-sm text-[#6B7280]">
              No puzzles yet. Generate a Daily Pack to create puzzles.
            </p>
          </div>
        ) : (
          <div className="divide-y divide-gray-100">
            {puzzles.map((puzzle) => (
              <div
                key={puzzle.id}
                className="flex items-center gap-3 py-3 px-1"
              >
                <div className="w-10 h-10 rounded-lg bg-purple-100 flex items-center justify-center shrink-0">
                  <Puzzle size={16} className="text-purple-600" />
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-semibold text-gray-900 truncate">
                    {PUZZLE_TYPE_LABELS[puzzle.type] || puzzle.type}
                  </p>
                  <p className="text-xs text-gray-500">
                    {puzzle.theme} · {puzzle.difficulty} ·{' '}
                    {new Date(puzzle.created_at).toLocaleDateString()}
                  </p>
                </div>
                <button
                  onClick={() => setPreview(puzzle)}
                  className="p-1.5 rounded-lg text-[#6B7280] hover:bg-gray-100"
                  title="Preview"
                >
                  <Eye size={16} />
                </button>
                <button
                  onClick={() => handleDelete(puzzle.id)}
                  className="p-1.5 rounded-lg text-red-400 hover:bg-red-50 hover:text-red-600"
                  title="Delete"
                >
                  <Trash2 size={16} />
                </button>
              </div>
            ))}
          </div>
        )}
      </Card>

      {/* Preview modal */}
      {preview && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4">
          <div className="bg-white rounded-2xl shadow-xl w-full max-w-lg max-h-[80vh] overflow-y-auto p-6">
            <div className="flex justify-between items-center mb-4">
              <h3 className="text-lg font-bold">
                {PUZZLE_TYPE_LABELS[preview.type] || preview.type}
              </h3>
              <button
                onClick={() => setPreview(null)}
                className="text-gray-400 hover:text-gray-700 text-xl"
              >
                ×
              </button>
            </div>
            <pre className="text-xs bg-gray-50 rounded-lg p-4 overflow-x-auto whitespace-pre-wrap">
              {JSON.stringify(preview.content, null, 2)}
            </pre>
          </div>
        </div>
      )}
    </div>
  )
}
